.PHONY: all clean

all:
	$(MAKE) -C AF_INET_TCP
	$(MAKE) -C AF_INET_UDP
	$(MAKE) -C AF_LOCAL_TCP
	$(MAKE) -C AF_LOCAL_UDP

clean:
	$(MAKE) -C AF_INET_TCP clean
	$(MAKE) -C AF_INET_UDP clean
	$(MAKE) -C AF_LOCAL_TCP clean
	$(MAKE) -C AF_LOCAL_UDP	clean